DATASET:
    train_list: ['Human36M']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 16
    use_gt_input: True

MODEL:
    name: 'GATOR'
    input_shape: [384, 288]
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    posenet_pretrained: False
    alpha: False

TRAIN:
    print_freq: 10
    batch_size: 64
    shuffle: True
    begin_epoch: 1
    end_epoch: 30
    edge_loss_start: 7
    scheduler: 'step'
    lr: 0.0001
    lr_step: [20]
    lr_factor: 0.95
    optimizer: 'adam'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
    vis: False
    weight_path: './results/3dpw.pth.tar'
